server:
  port: 8086
spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile:
        - local
  kafka:
    topic: coffee-orders-demo
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: coffee-orders-demo-grp
      auto-offset-reset: earliest
    properties:
      schema:
        registry:
          url: http://localhost:8081

