server:
  port: 8085
spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic: "bathirdparty-library-events"
    producer:
      bootstrap-servers: 34.205.74.247:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        retries: 10
        acks: 1

    admin:
      properties:
        bootstrap-servers: 34.205.74.247:9092
