/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bookapp.example.booksproducer.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BooksAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3278855812706809814L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BooksAvro\",\"namespace\":\"com.bookapp.example.booksproducer.avro\",\"fields\":[{\"name\":\"bookID\",\"type\":\"int\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"authors\",\"type\":\"string\"},{\"name\":\"average_rating\",\"type\":\"double\"},{\"name\":\"isbn\",\"type\":\"string\"},{\"name\":\"isbn13\",\"type\":\"string\"},{\"name\":\"language_code\",\"type\":\"string\"},{\"name\":\"num_pages\",\"type\":\"int\"},{\"name\":\"ratings_count\",\"type\":\"int\"},{\"name\":\"text_reviews_count\",\"type\":\"int\"},{\"name\":\"publication_date\",\"type\":\"string\"},{\"name\":\"publisher\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BooksAvro> ENCODER =
      new BinaryMessageEncoder<BooksAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BooksAvro> DECODER =
      new BinaryMessageDecoder<BooksAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BooksAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BooksAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BooksAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BooksAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BooksAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BooksAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BooksAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BooksAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int bookID;
  @Deprecated public java.lang.CharSequence title;
  @Deprecated public java.lang.CharSequence authors;
  @Deprecated public double average_rating;
  @Deprecated public java.lang.CharSequence isbn;
  @Deprecated public java.lang.CharSequence isbn13;
  @Deprecated public java.lang.CharSequence language_code;
  @Deprecated public int num_pages;
  @Deprecated public int ratings_count;
  @Deprecated public int text_reviews_count;
  @Deprecated public java.lang.CharSequence publication_date;
  @Deprecated public java.lang.CharSequence publisher;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BooksAvro() {}

  /**
   * All-args constructor.
   * @param bookID The new value for bookID
   * @param title The new value for title
   * @param authors The new value for authors
   * @param average_rating The new value for average_rating
   * @param isbn The new value for isbn
   * @param isbn13 The new value for isbn13
   * @param language_code The new value for language_code
   * @param num_pages The new value for num_pages
   * @param ratings_count The new value for ratings_count
   * @param text_reviews_count The new value for text_reviews_count
   * @param publication_date The new value for publication_date
   * @param publisher The new value for publisher
   */
  public BooksAvro(java.lang.Integer bookID, java.lang.CharSequence title, java.lang.CharSequence authors, java.lang.Double average_rating, java.lang.CharSequence isbn, java.lang.CharSequence isbn13, java.lang.CharSequence language_code, java.lang.Integer num_pages, java.lang.Integer ratings_count, java.lang.Integer text_reviews_count, java.lang.CharSequence publication_date, java.lang.CharSequence publisher) {
    this.bookID = bookID;
    this.title = title;
    this.authors = authors;
    this.average_rating = average_rating;
    this.isbn = isbn;
    this.isbn13 = isbn13;
    this.language_code = language_code;
    this.num_pages = num_pages;
    this.ratings_count = ratings_count;
    this.text_reviews_count = text_reviews_count;
    this.publication_date = publication_date;
    this.publisher = publisher;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bookID;
    case 1: return title;
    case 2: return authors;
    case 3: return average_rating;
    case 4: return isbn;
    case 5: return isbn13;
    case 6: return language_code;
    case 7: return num_pages;
    case 8: return ratings_count;
    case 9: return text_reviews_count;
    case 10: return publication_date;
    case 11: return publisher;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bookID = (java.lang.Integer)value$; break;
    case 1: title = (java.lang.CharSequence)value$; break;
    case 2: authors = (java.lang.CharSequence)value$; break;
    case 3: average_rating = (java.lang.Double)value$; break;
    case 4: isbn = (java.lang.CharSequence)value$; break;
    case 5: isbn13 = (java.lang.CharSequence)value$; break;
    case 6: language_code = (java.lang.CharSequence)value$; break;
    case 7: num_pages = (java.lang.Integer)value$; break;
    case 8: ratings_count = (java.lang.Integer)value$; break;
    case 9: text_reviews_count = (java.lang.Integer)value$; break;
    case 10: publication_date = (java.lang.CharSequence)value$; break;
    case 11: publisher = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'bookID' field.
   * @return The value of the 'bookID' field.
   */
  public int getBookID() {
    return bookID;
  }


  /**
   * Sets the value of the 'bookID' field.
   * @param value the value to set.
   */
  public void setBookID(int value) {
    this.bookID = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'authors' field.
   * @return The value of the 'authors' field.
   */
  public java.lang.CharSequence getAuthors() {
    return authors;
  }


  /**
   * Sets the value of the 'authors' field.
   * @param value the value to set.
   */
  public void setAuthors(java.lang.CharSequence value) {
    this.authors = value;
  }

  /**
   * Gets the value of the 'average_rating' field.
   * @return The value of the 'average_rating' field.
   */
  public double getAverageRating() {
    return average_rating;
  }


  /**
   * Sets the value of the 'average_rating' field.
   * @param value the value to set.
   */
  public void setAverageRating(double value) {
    this.average_rating = value;
  }

  /**
   * Gets the value of the 'isbn' field.
   * @return The value of the 'isbn' field.
   */
  public java.lang.CharSequence getIsbn() {
    return isbn;
  }


  /**
   * Sets the value of the 'isbn' field.
   * @param value the value to set.
   */
  public void setIsbn(java.lang.CharSequence value) {
    this.isbn = value;
  }

  /**
   * Gets the value of the 'isbn13' field.
   * @return The value of the 'isbn13' field.
   */
  public java.lang.CharSequence getIsbn13() {
    return isbn13;
  }


  /**
   * Sets the value of the 'isbn13' field.
   * @param value the value to set.
   */
  public void setIsbn13(java.lang.CharSequence value) {
    this.isbn13 = value;
  }

  /**
   * Gets the value of the 'language_code' field.
   * @return The value of the 'language_code' field.
   */
  public java.lang.CharSequence getLanguageCode() {
    return language_code;
  }


  /**
   * Sets the value of the 'language_code' field.
   * @param value the value to set.
   */
  public void setLanguageCode(java.lang.CharSequence value) {
    this.language_code = value;
  }

  /**
   * Gets the value of the 'num_pages' field.
   * @return The value of the 'num_pages' field.
   */
  public int getNumPages() {
    return num_pages;
  }


  /**
   * Sets the value of the 'num_pages' field.
   * @param value the value to set.
   */
  public void setNumPages(int value) {
    this.num_pages = value;
  }

  /**
   * Gets the value of the 'ratings_count' field.
   * @return The value of the 'ratings_count' field.
   */
  public int getRatingsCount() {
    return ratings_count;
  }


  /**
   * Sets the value of the 'ratings_count' field.
   * @param value the value to set.
   */
  public void setRatingsCount(int value) {
    this.ratings_count = value;
  }

  /**
   * Gets the value of the 'text_reviews_count' field.
   * @return The value of the 'text_reviews_count' field.
   */
  public int getTextReviewsCount() {
    return text_reviews_count;
  }


  /**
   * Sets the value of the 'text_reviews_count' field.
   * @param value the value to set.
   */
  public void setTextReviewsCount(int value) {
    this.text_reviews_count = value;
  }

  /**
   * Gets the value of the 'publication_date' field.
   * @return The value of the 'publication_date' field.
   */
  public java.lang.CharSequence getPublicationDate() {
    return publication_date;
  }


  /**
   * Sets the value of the 'publication_date' field.
   * @param value the value to set.
   */
  public void setPublicationDate(java.lang.CharSequence value) {
    this.publication_date = value;
  }

  /**
   * Gets the value of the 'publisher' field.
   * @return The value of the 'publisher' field.
   */
  public java.lang.CharSequence getPublisher() {
    return publisher;
  }


  /**
   * Sets the value of the 'publisher' field.
   * @param value the value to set.
   */
  public void setPublisher(java.lang.CharSequence value) {
    this.publisher = value;
  }

  /**
   * Creates a new BooksAvro RecordBuilder.
   * @return A new BooksAvro RecordBuilder
   */
  public static com.bookapp.example.booksproducer.avro.BooksAvro.Builder newBuilder() {
    return new com.bookapp.example.booksproducer.avro.BooksAvro.Builder();
  }

  /**
   * Creates a new BooksAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BooksAvro RecordBuilder
   */
  public static com.bookapp.example.booksproducer.avro.BooksAvro.Builder newBuilder(com.bookapp.example.booksproducer.avro.BooksAvro.Builder other) {
    if (other == null) {
      return new com.bookapp.example.booksproducer.avro.BooksAvro.Builder();
    } else {
      return new com.bookapp.example.booksproducer.avro.BooksAvro.Builder(other);
    }
  }

  /**
   * Creates a new BooksAvro RecordBuilder by copying an existing BooksAvro instance.
   * @param other The existing instance to copy.
   * @return A new BooksAvro RecordBuilder
   */
  public static com.bookapp.example.booksproducer.avro.BooksAvro.Builder newBuilder(com.bookapp.example.booksproducer.avro.BooksAvro other) {
    if (other == null) {
      return new com.bookapp.example.booksproducer.avro.BooksAvro.Builder();
    } else {
      return new com.bookapp.example.booksproducer.avro.BooksAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for BooksAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BooksAvro>
    implements org.apache.avro.data.RecordBuilder<BooksAvro> {

    private int bookID;
    private java.lang.CharSequence title;
    private java.lang.CharSequence authors;
    private double average_rating;
    private java.lang.CharSequence isbn;
    private java.lang.CharSequence isbn13;
    private java.lang.CharSequence language_code;
    private int num_pages;
    private int ratings_count;
    private int text_reviews_count;
    private java.lang.CharSequence publication_date;
    private java.lang.CharSequence publisher;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bookapp.example.booksproducer.avro.BooksAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bookID)) {
        this.bookID = data().deepCopy(fields()[0].schema(), other.bookID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.authors)) {
        this.authors = data().deepCopy(fields()[2].schema(), other.authors);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.average_rating)) {
        this.average_rating = data().deepCopy(fields()[3].schema(), other.average_rating);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.isbn)) {
        this.isbn = data().deepCopy(fields()[4].schema(), other.isbn);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.isbn13)) {
        this.isbn13 = data().deepCopy(fields()[5].schema(), other.isbn13);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.language_code)) {
        this.language_code = data().deepCopy(fields()[6].schema(), other.language_code);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.num_pages)) {
        this.num_pages = data().deepCopy(fields()[7].schema(), other.num_pages);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.ratings_count)) {
        this.ratings_count = data().deepCopy(fields()[8].schema(), other.ratings_count);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.text_reviews_count)) {
        this.text_reviews_count = data().deepCopy(fields()[9].schema(), other.text_reviews_count);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.publication_date)) {
        this.publication_date = data().deepCopy(fields()[10].schema(), other.publication_date);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.publisher)) {
        this.publisher = data().deepCopy(fields()[11].schema(), other.publisher);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing BooksAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bookapp.example.booksproducer.avro.BooksAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.bookID)) {
        this.bookID = data().deepCopy(fields()[0].schema(), other.bookID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.title)) {
        this.title = data().deepCopy(fields()[1].schema(), other.title);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.authors)) {
        this.authors = data().deepCopy(fields()[2].schema(), other.authors);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.average_rating)) {
        this.average_rating = data().deepCopy(fields()[3].schema(), other.average_rating);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.isbn)) {
        this.isbn = data().deepCopy(fields()[4].schema(), other.isbn);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.isbn13)) {
        this.isbn13 = data().deepCopy(fields()[5].schema(), other.isbn13);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.language_code)) {
        this.language_code = data().deepCopy(fields()[6].schema(), other.language_code);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.num_pages)) {
        this.num_pages = data().deepCopy(fields()[7].schema(), other.num_pages);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.ratings_count)) {
        this.ratings_count = data().deepCopy(fields()[8].schema(), other.ratings_count);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.text_reviews_count)) {
        this.text_reviews_count = data().deepCopy(fields()[9].schema(), other.text_reviews_count);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.publication_date)) {
        this.publication_date = data().deepCopy(fields()[10].schema(), other.publication_date);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.publisher)) {
        this.publisher = data().deepCopy(fields()[11].schema(), other.publisher);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'bookID' field.
      * @return The value.
      */
    public int getBookID() {
      return bookID;
    }


    /**
      * Sets the value of the 'bookID' field.
      * @param value The value of 'bookID'.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder setBookID(int value) {
      validate(fields()[0], value);
      this.bookID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bookID' field has been set.
      * @return True if the 'bookID' field has been set, false otherwise.
      */
    public boolean hasBookID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bookID' field.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder clearBookID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.title = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder clearTitle() {
      title = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'authors' field.
      * @return The value.
      */
    public java.lang.CharSequence getAuthors() {
      return authors;
    }


    /**
      * Sets the value of the 'authors' field.
      * @param value The value of 'authors'.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder setAuthors(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.authors = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'authors' field has been set.
      * @return True if the 'authors' field has been set, false otherwise.
      */
    public boolean hasAuthors() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'authors' field.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder clearAuthors() {
      authors = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'average_rating' field.
      * @return The value.
      */
    public double getAverageRating() {
      return average_rating;
    }


    /**
      * Sets the value of the 'average_rating' field.
      * @param value The value of 'average_rating'.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder setAverageRating(double value) {
      validate(fields()[3], value);
      this.average_rating = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'average_rating' field has been set.
      * @return True if the 'average_rating' field has been set, false otherwise.
      */
    public boolean hasAverageRating() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'average_rating' field.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder clearAverageRating() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'isbn' field.
      * @return The value.
      */
    public java.lang.CharSequence getIsbn() {
      return isbn;
    }


    /**
      * Sets the value of the 'isbn' field.
      * @param value The value of 'isbn'.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder setIsbn(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.isbn = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'isbn' field has been set.
      * @return True if the 'isbn' field has been set, false otherwise.
      */
    public boolean hasIsbn() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'isbn' field.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder clearIsbn() {
      isbn = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'isbn13' field.
      * @return The value.
      */
    public java.lang.CharSequence getIsbn13() {
      return isbn13;
    }


    /**
      * Sets the value of the 'isbn13' field.
      * @param value The value of 'isbn13'.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder setIsbn13(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.isbn13 = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'isbn13' field has been set.
      * @return True if the 'isbn13' field has been set, false otherwise.
      */
    public boolean hasIsbn13() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'isbn13' field.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder clearIsbn13() {
      isbn13 = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'language_code' field.
      * @return The value.
      */
    public java.lang.CharSequence getLanguageCode() {
      return language_code;
    }


    /**
      * Sets the value of the 'language_code' field.
      * @param value The value of 'language_code'.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder setLanguageCode(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.language_code = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'language_code' field has been set.
      * @return True if the 'language_code' field has been set, false otherwise.
      */
    public boolean hasLanguageCode() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'language_code' field.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder clearLanguageCode() {
      language_code = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'num_pages' field.
      * @return The value.
      */
    public int getNumPages() {
      return num_pages;
    }


    /**
      * Sets the value of the 'num_pages' field.
      * @param value The value of 'num_pages'.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder setNumPages(int value) {
      validate(fields()[7], value);
      this.num_pages = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'num_pages' field has been set.
      * @return True if the 'num_pages' field has been set, false otherwise.
      */
    public boolean hasNumPages() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'num_pages' field.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder clearNumPages() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'ratings_count' field.
      * @return The value.
      */
    public int getRatingsCount() {
      return ratings_count;
    }


    /**
      * Sets the value of the 'ratings_count' field.
      * @param value The value of 'ratings_count'.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder setRatingsCount(int value) {
      validate(fields()[8], value);
      this.ratings_count = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'ratings_count' field has been set.
      * @return True if the 'ratings_count' field has been set, false otherwise.
      */
    public boolean hasRatingsCount() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'ratings_count' field.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder clearRatingsCount() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'text_reviews_count' field.
      * @return The value.
      */
    public int getTextReviewsCount() {
      return text_reviews_count;
    }


    /**
      * Sets the value of the 'text_reviews_count' field.
      * @param value The value of 'text_reviews_count'.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder setTextReviewsCount(int value) {
      validate(fields()[9], value);
      this.text_reviews_count = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'text_reviews_count' field has been set.
      * @return True if the 'text_reviews_count' field has been set, false otherwise.
      */
    public boolean hasTextReviewsCount() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'text_reviews_count' field.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder clearTextReviewsCount() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'publication_date' field.
      * @return The value.
      */
    public java.lang.CharSequence getPublicationDate() {
      return publication_date;
    }


    /**
      * Sets the value of the 'publication_date' field.
      * @param value The value of 'publication_date'.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder setPublicationDate(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.publication_date = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'publication_date' field has been set.
      * @return True if the 'publication_date' field has been set, false otherwise.
      */
    public boolean hasPublicationDate() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'publication_date' field.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder clearPublicationDate() {
      publication_date = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'publisher' field.
      * @return The value.
      */
    public java.lang.CharSequence getPublisher() {
      return publisher;
    }


    /**
      * Sets the value of the 'publisher' field.
      * @param value The value of 'publisher'.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder setPublisher(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.publisher = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'publisher' field has been set.
      * @return True if the 'publisher' field has been set, false otherwise.
      */
    public boolean hasPublisher() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'publisher' field.
      * @return This builder.
      */
    public com.bookapp.example.booksproducer.avro.BooksAvro.Builder clearPublisher() {
      publisher = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BooksAvro build() {
      try {
        BooksAvro record = new BooksAvro();
        record.bookID = fieldSetFlags()[0] ? this.bookID : (java.lang.Integer) defaultValue(fields()[0]);
        record.title = fieldSetFlags()[1] ? this.title : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.authors = fieldSetFlags()[2] ? this.authors : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.average_rating = fieldSetFlags()[3] ? this.average_rating : (java.lang.Double) defaultValue(fields()[3]);
        record.isbn = fieldSetFlags()[4] ? this.isbn : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.isbn13 = fieldSetFlags()[5] ? this.isbn13 : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.language_code = fieldSetFlags()[6] ? this.language_code : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.num_pages = fieldSetFlags()[7] ? this.num_pages : (java.lang.Integer) defaultValue(fields()[7]);
        record.ratings_count = fieldSetFlags()[8] ? this.ratings_count : (java.lang.Integer) defaultValue(fields()[8]);
        record.text_reviews_count = fieldSetFlags()[9] ? this.text_reviews_count : (java.lang.Integer) defaultValue(fields()[9]);
        record.publication_date = fieldSetFlags()[10] ? this.publication_date : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.publisher = fieldSetFlags()[11] ? this.publisher : (java.lang.CharSequence) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BooksAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<BooksAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BooksAvro>
    READER$ = (org.apache.avro.io.DatumReader<BooksAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.bookID);

    out.writeString(this.title);

    out.writeString(this.authors);

    out.writeDouble(this.average_rating);

    out.writeString(this.isbn);

    out.writeString(this.isbn13);

    out.writeString(this.language_code);

    out.writeInt(this.num_pages);

    out.writeInt(this.ratings_count);

    out.writeInt(this.text_reviews_count);

    out.writeString(this.publication_date);

    out.writeString(this.publisher);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.bookID = in.readInt();

      this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);

      this.authors = in.readString(this.authors instanceof Utf8 ? (Utf8)this.authors : null);

      this.average_rating = in.readDouble();

      this.isbn = in.readString(this.isbn instanceof Utf8 ? (Utf8)this.isbn : null);

      this.isbn13 = in.readString(this.isbn13 instanceof Utf8 ? (Utf8)this.isbn13 : null);

      this.language_code = in.readString(this.language_code instanceof Utf8 ? (Utf8)this.language_code : null);

      this.num_pages = in.readInt();

      this.ratings_count = in.readInt();

      this.text_reviews_count = in.readInt();

      this.publication_date = in.readString(this.publication_date instanceof Utf8 ? (Utf8)this.publication_date : null);

      this.publisher = in.readString(this.publisher instanceof Utf8 ? (Utf8)this.publisher : null);

    } else {
      for (int i = 0; i < 12; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.bookID = in.readInt();
          break;

        case 1:
          this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          break;

        case 2:
          this.authors = in.readString(this.authors instanceof Utf8 ? (Utf8)this.authors : null);
          break;

        case 3:
          this.average_rating = in.readDouble();
          break;

        case 4:
          this.isbn = in.readString(this.isbn instanceof Utf8 ? (Utf8)this.isbn : null);
          break;

        case 5:
          this.isbn13 = in.readString(this.isbn13 instanceof Utf8 ? (Utf8)this.isbn13 : null);
          break;

        case 6:
          this.language_code = in.readString(this.language_code instanceof Utf8 ? (Utf8)this.language_code : null);
          break;

        case 7:
          this.num_pages = in.readInt();
          break;

        case 8:
          this.ratings_count = in.readInt();
          break;

        case 9:
          this.text_reviews_count = in.readInt();
          break;

        case 10:
          this.publication_date = in.readString(this.publication_date instanceof Utf8 ? (Utf8)this.publication_date : null);
          break;

        case 11:
          this.publisher = in.readString(this.publisher instanceof Utf8 ? (Utf8)this.publisher : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










