
version: '3'

services:
  appdb:
    image: mysql:5.7.22
    container_name: appdb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: abc123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - /home/esak/db-eks/db:/var/lib/mysql
      - /home/esak/db-eks/db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local

