CREATE DATABASE sales;

psql -d sales 

CREATE TABLE EMPLOYEE_TXS
(
	TXN_ID integer	 NOT NULL,
	SENDER_NM VARCHAR ( 150 ) NOT NULL, 
	RECEIVER_NM VARCHAR ( 150 ) NOT NULL, 
	SENDER_ACCT_NM VARCHAR ( 50 ) NOT NULL,
	RECEIVER_ACCT_NM VARCHAR ( 50 ) NOT NULL,
	AMNT integer, 
	SENDER_BNK VARCHAR ( 150 ) NOT NULL, 
	TXN_DT TIMESTAMP
	
);


INSERT INTO EMPLOYEE_TXS (TXN_ID ,SENDER_NM , RECEIVER_NM , SENDER_ACCT_NM ,RECEIVER_ACCT_NM ,AMNT , SENDER_BNK , TXN_DT )
VALUES ( 1, 'CMPNY', 'ESAKKI', 'CMPAX122', 'ESAK123v1', 7843, 'RBI', NOW() )
INSERT INTO EMPLOYEE_TXS (TXN_ID ,SENDER_NM , RECEIVER_NM , SENDER_ACCT_NM ,RECEIVER_ACCT_NM ,AMNT , SENDER_BNK , TXN_DT )
VALUES ( 2, 'CMPNY2', 'ESAKKI2', 'CMPAX122', 'ESAK223v1', 843, 'RBI', NOW() )
INSERT INTO EMPLOYEE_TXS (TXN_ID ,SENDER_NM , RECEIVER_NM , SENDER_ACCT_NM ,RECEIVER_ACCT_NM ,AMNT , SENDER_BNK , TXN_DT )
VALUES ( 3, 'CMPNY3', 'ESAKKI3', 'CMPAX122', 'ESAK323v1', 743, 'RBI', NOW() )
INSERT INTO EMPLOYEE_TXS (TXN_ID ,SENDER_NM , RECEIVER_NM , SENDER_ACCT_NM ,RECEIVER_ACCT_NM ,AMNT , SENDER_BNK , TXN_DT )
VALUES ( 4, 'CMPNY4', 'ESAKKI4', 'CMPAX122', 'ESAK423v1', 78, 'RBI', NOW() )
INSERT INTO EMPLOYEE_TXS (TXN_ID ,SENDER_NM , RECEIVER_NM , SENDER_ACCT_NM ,RECEIVER_ACCT_NM ,AMNT , SENDER_BNK , TXN_DT )
VALUES ( 5, 'CMPNY5', 'ESAKKI5', 'CMPAX122', 'ESAK523v1', 7843, 'RBI', NOW() )
