server:
  port: 9098

slack:
  webhook: https://hooks.slack.com/services/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

spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile:
        - local
  kafka:
    topic: "sales-events-1A-example"
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: sales-orders-demo-grp
      auto-offset-reset: earliest
      properties:
        schema:
          registry:
            url: http://localhost:8081
    admin:
      properties:
        bootstrap-servers: localhost:9092

